config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'groups#index'

  resources :groups, only: [:index, :new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end

  resources :users, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  validates :users, presence: true

  has_many :group_users
  has_many :users, through: :group_users
  accepts_nested_attributes_for :users
  has_many :messages
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
  has_many :messages

  validates :group, presence: true
  validates :user, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  belongs_to :group

  def to_api_json
    {
      name: user.name,
      created_at: created_at.strftime('%m/%d %p %H:%M'),
      body: body,
      image_url: image.to_s
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :set_group, only: [:edit, :update]
  before_action :authenticate_user!

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_messages_path(@group), notice: 'チャットグループが作成されました。' }
        format.json
      else
        format.html { render :new }
        format.json
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_messages_path(@group), notice: 'グループが更新されました。' }
        format.json
      else
        format.html { render :edit }
        format.json
      end
    end
  end

  def set_group
    @group = Group.find(params[:id])
  end

  private

  def group_params
    params.require(:group).permit(:name, user_ids:[])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_group,:set_messages, only: [:index, :create]

  def index
    @message = Message.new

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @group.messages.includes(:user).map(&:to_api_json) }
    end
  end

  def create
    @message = current_user.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'}
        format.json
      end
    else
      flash.now.alert = 'メッセージを入力して下さい'
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:body, :image).merge(group_id: params[:group_id], user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_messages
    @messages = @group.messages.includes(:user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where('name LIKE ?', "%#{params[:name]}%")
    render json: @users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, 'グループ名', class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label 'チャットメンバーを追加', class: 'chat-group-form__label'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{ type: "search", placeholder: '追加したいユーザー名を入力してください' }
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label 'チャットメンバー', class: 'chat-group-form__label'
    .chat-group-form__field--right
      #chat-group-users
        - @group.users.each do |user|
          .chat-group-user.clearfix{ id: "chat-group-user-#{user.id}" }
            %input{ type: "hidden", name: "group[user_ids][]", value: user.id }
            %p.chat-group-user__name= user.name
            - unless user.id == current_user.id
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove{ 'data-user-id': user.id } 削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit 'Save', class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render 'form'

app/views/groups/index.html.haml
.chat
  .chat-side
    .chat-side__user
      %h5= current_user.name
      =link_to edit_user_registration_path do
        = fa_icon 'cog'
      =link_to new_group_path do
        = fa_icon 'pencil-square-o'
    .chat-side__groups
      = render partial: "layouts/group"
  .chat-main
    .chat-main__header
      .chat-main__header__left
        %h2 Sampleグループ
        %p Members: yosuketokunaga
      .chat-main__header__right
        =link_to 'Edit', ""
    .chat-main__body
    

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form'

app/views/layouts/_flashmessage.html.haml
- flash.each do |key, value|
  - key = "info" if key == "notice"
  - key = "danger"  if key == "alert"
  = content_tag :div, value, class: "alert alert-#{key}"

app/views/layouts/_group.html.haml
- current_user.groups.each do |group|
  = link_to group_messages_path(group) do
    .chat-side__group
      %p.chat__group__name
        = group.name
      %p.chat__group__message
        - if group.messages.last
          = group.messages.last.body
        - else
          まだメッセージはありません。

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render "layouts/flashmessage"
    = yield

app/views/messages/_header.html.haml
.chat-main__header__left
  %h2
    = group.name
  %p
    - group.users.each do |user|
      = user.name
.chat-main__header__right
  =link_to 'Edit', edit_group_path(group)

app/views/messages/_message.html.haml
.chat-main__body__name
  = message.user.name
.chat-main__body__date
  = l(message.created_at, format: :custom)
.chat-main__body__message
  = message.body
.chat-main__body__image
  - if message.image?
    = image_tag message.image

app/views/messages/index.html.haml
.chat
  .chat-side
    .chat-side__user
      %h5= current_user.name
      =link_to edit_user_registration_path do
        = fa_icon 'cog'
      =link_to new_group_path do
        = fa_icon 'pencil-square-o'
    .chat-side__groups
      = render partial: "layouts/group"
  .chat-main
    .chat-main__header
      = render partial: 'header', locals:{ group: @group }
    .chat-main__body
      .chat-main__body__messages
        = render @messages

  .chat-footer
    = form_for [@group, @message] do |f|
      .chat-footer__body
        = f.text_area :body, row: 1, placeholder: 'type a message'
        %label.chat-footer__file
          = f.file_field :image
          %i.fa.fa-image
      = f.submit 'Send'